# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dd6f0bdb20bbce117d1b0fd13a053911bdd00079744edc42a2ef727c466c35bf671305cc301b6b9b92d85d190c5f9f22bc46d0b12d6814e3c152d2331ae709e

test:
  secret_key_base: 45c7d1b149e70cad7ec64ae72dacb509a123b24e7ed3989b080f63f2c135a15435c48e2e7c63ec0a72a49a8373729dc5832484a82cd8422a25c85507bff53785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
